spring:
  datasource: #mybatisplus数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.0.4:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

flask:
  server: 10.10.0.2:2333

server:
  port: 2233

admin:
  user: admin
  password: 123456

email:
  Mail_server: smtp.qq.com  # 使用的邮箱服务
  Mail_user: 402887431@qq.com  # 使用邮箱服务账户
  Mail_pass: wfjstvcrxndybgbh  # 邮箱服务密码或授权码
  Mail_port: 465
  SSL: true